steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    id: test
    args:
      - -c
      - |
        echo "HERE _BODY ${_BODY} and _BRANCH_NAME ${_BRANCH_NAME} and _LABEL_NAME ${_LABEL_NAME} and _CHECK_RUN_ID ${_CHECK_RUN_ID} and _ACCESS_TOKEN ${_ACCESS_TOKEN} build_id=$BUILD_ID"

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    id: testSuccess
    args:
      - -c
      - |
        exit 0

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    id: testFailure
    args:
      - -c
      - |
        exit 1

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    id: setStatus
    waitFor: [ 'test', 'testSuccess', 'testFailure' ]
    args:
      - -c
      - |
        if [[ "${_BUILD_STATUS[test]}" == "SUCCESS" && "${_BUILD_STATUS[testSuccess]}" == "SUCCESS" && "${_BUILD_STATUS[testFailure]}" == "SUCCESS" ]]; then
          STATUS="success"
         else 
         STATUS="failure" 
         fi        
         echo "STATUS=$STATUS" > /workspace/status.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        STATUS=$(cat /workspace/status.txt)
        echo "Final status: $STATUS"

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: bash
    if: always()
    args:
      - -c
      - |
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $_ACCESS_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/helaouislim/training_ci_cd/check-runs/$_CHECK_RUN_ID \
          -d '{"name": "mighty_readme","started_at": "2018-05-04T01:14:52Z","status": "completed","conclusion": "success","completed_at": "2018-05-04T01:14:52Z","output": {"title": "Mighty Readme report","summary": "There are 0 failures, 2 warnings, and 1 notices.","text": "You may have some misspelled words on lines 2 and 4. You also may want to add a section in your README about how to install your app."}}'


substitutions:
  _BODY: '$(body)'
  _BRANCH_NAME: '$(body.BRANCH_NAME)'
  _LABEL_NAME: '$(body.LABEL_NAME)'
  _CHECK_RUN_ID: '$(body.CHECK_RUN_ID)'
  _ACCESS_TOKEN: '$(body.ACCESS_TOKEN)'
