steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "HERE _BODY ${_BODY} and _BRANCH_NAME ${_BRANCH_NAME} and BRANCH_NAME ${BRANCH_NAME}"
substitutions:
  _BODY: $(body)
  BRANCH_NAME: $(body.BRANCH_NAME)
