steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "HERE _BODY ${_BODY} and _BRANCH_NAME ${_BRANCH_NAME} and _LABEL_NAME ${_LABEL_NAME}"

substitutions:
  _BODY: '$(body)'
  _BRANCH_NAME: '$(body.BRANCH_NAME)'
  _LABEL_NAME: '$(body.LABEL_NAME)'
