name: 'PR Title Check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
      - edited

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          # Match pull request titles in the form "[JIRA-TICKET] TYPE : Details".
          regexp: "(^\\[[a-zA-Z]+-\\d+\\]\\s[a-zA-Z]+\\s?:\\s?.+|^release.*)"
          helpMessage: "Example: '[CORE-1234] FEAT : example of title'"
      - name: Create a check run"
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
          PROJECT_NAME: "striped-temple-418614"
          TRIGGER_NAME: "test-webhook-label"
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/helaouislim/training_ci_cd/check-runs" \
            -d '{"name":"mighty_readme","head_sha":"${{ github.event.pull_request.head.sha }}","status":"in_progress","external_id":"42","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"","text":""}}'
