name: GitHub Actions Demo
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'build_apk' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
          PROJECT_NAME: "striped-temple-418614"
          TRIGGER_NAME: "test-webhook-label"
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -e "github.com" \
            "https://cloudbuild.googleapis.com/v1/projects/${PROJECT_NAME}/locations/global/triggers/${TRIGGER_NAME}:webhook?key=${WEBHOOK_KEY}&secret=${WEBHOOK_SECRET}&trigger=${TRIGGER_NAME}&projectId=${PROJECT_NAME}" -d '{"BRANCH_NAME": "${{ github.head_ref }}", "LABEL_NAME": "${{ github.event.label.name }}"}'
