name: Update Check Run

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  update_check_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate JWT and get Installation ID and Token
        run: |
          JWT=$(python3 generate_jwt.py ${{ secrets.GITHUB_APP_ID }} ${{ secrets.GITHUB_APP_PRIVATE_KEY }})
          INSTALLATION_ID=$(curl -s -X GET \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations \
            | jq -r '.[0].id')

          ACCESS_TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens \
            | jq -r '.token')

          echo "INSTALLATION_ID=$INSTALLATION_ID" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Update Check Run
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/helaouislim/training_ci_cd/check-runs/25466798712 \
            -d '{
              "name": "mighty_readme",
              "started_at": "2018-05-04T01:14:52Z",
              "status": "completed",
              "conclusion": "success",
              "completed_at": "2018-05-04T01:14:52Z",
              "output": {
                "title": "Mighty Readme report",
                "summary": "There are 0 failures, 2 warnings, and 1 notices.",
                "text": "You may have some misspelled words on lines 2 and 4. You also may want to add a section in your README about how to install your app.",
                "annotations": [
                  {
                    "path": "README.md",
                    "annotation_level": "warning",
                    "title": "Spell Checker",
                    "message": "Check your spelling for 'banaas'.",
                    "raw_details": "Do you mean 'bananas' or 'banana'?",
                    "start_line": 2,
                    "end_line": 2
                  },
                  {
                    "path": "README.md",
                    "annotation_level": "warning",
                    "title": "Spell Checker",
                    "message": "Check your spelling for 'aples'",
                    "raw_details": "Do you mean 'apples' or 'Naples'?",
                    "start_line": 4,
                    "end_line": 4
                  }
                ],
                "images": [
                  {
                    "alt": "Super bananas",
                    "image_url": "http://example.com/images/42"
                  }
                ]
              }
            }'
        env:
          GITHUB_APP_ID_SECRET: ${{ secrets.APP_ID }}
          GITHUB_APP_PRIVATE_KEY_SECRET: ${{ secrets.APP_PRIVATE_KEY }}
