name: Update Check Run

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  update_check_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate JWT and get Installation ID and Token
        run: |
          JWT=$(python3 generate_jwt.py)
          INSTALLATION_ID=$(curl -s -X GET \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations \
            | jq -r '.[0].id')

          ACCESS_TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens \
            | jq -r '.token')

          echo "INSTALLATION_ID=$INSTALLATION_ID" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Update Check Run
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/helaouislim/training_ci_cd/check-runs \
             -d '{"name":"instrumented-tests","head_sha":"54a3c8ed5dad13831c7271c1704af7a97e1fa307","status":"in_progress","external_id":"42","started_at":"2024-04-29T09:00:00Z","output":{"title":"instrumented tests2","summary":"","text":""}}'
        env:
          GITHUB_APP_ID_SECRET: ${{ secrets.APP_ID }}
          GITHUB_APP_PRIVATE_KEY_SECRET: ${{ secrets.APP_PRIVATE_KEY }}
